FROM python:3.9-slim
WORKDIR /app
RUN apt-get update && \
    apt-get install -y curl gcc libgomp1 && \
    rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p /app/model
COPY . .
EXPOSE 8001
CMD ["python", "app.py"]
