global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'vm-migration-api'
    static_configs:
      - targets: ['api:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
# global:
#   scrape_interval: 5s
#   evaluation_interval: 5s
#   scrape_timeout: 4s  # Added timeout

# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090']

#   - job_name: 'node'
#     static_configs:
#       - targets: ['node-exporter:9100']
#     # Added relabeling for better metric consistency
#     relabel_configs:
#       - source_labels: [__address__]
#         target_label: instance
#         regex: '(.*):\d+'
#         replacement: '${1}'

#   - job_name: 'vm-migration-api'
#     static_configs:
#       - targets: ['api:8001']
#     metrics_path: '/metrics'
#     scrape_interval: 10s
